/*
 * generated by Xtext
 */
package fr.inria.atlanmod.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.atlanmod.ui.internal.JsonActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JsonExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JsonActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JsonActivator.getInstance().getInjector(JsonActivator.FR_INRIA_ATLANMOD_JSON);
	}
	
}
