/*
 * generated by Xtext
 */
package fr.inria.atlanmod;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends fr.inria.atlanmod.AbstractJsonRuntimeModule {

}
