<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="googlePlaces" nsURI="http://fr.inria.atlanmod/discovered/googlePlaces"
    nsPrefix="composedg">
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Result" value="2"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" lowerBound="1"
        eType="#//Geometry">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="geometry" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="icon" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="id" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="name" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="reference" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="types" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vicinity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="vicinity" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatted_address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="formatted_address" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatted_phone_number"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="formatted_phone_number" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="international_phone_number"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="international_phone_number" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="rating" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="url" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utc_offset" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="utc_offset" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="website" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address_components" lowerBound="1"
        upperBound="-1" eType="#//Address_component">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="address_components" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="photos" lowerBound="1"
        upperBound="-1" eType="#//Photo">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="photos" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviews" lowerBound="1"
        upperBound="-1" eType="#//Aspect">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="reviews" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Northeast">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Northeast" value="1"/>
        <details key="Location" value="2"/>
        <details key="Southwest" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="4"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="lat" value="4"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Northeast" value="1"/>
          <details key="Location" value="2"/>
          <details key="Southwest" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="4"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lng" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="lng" value="4"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Northeast" value="1"/>
          <details key="Location" value="2"/>
          <details key="Southwest" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="4"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aspect">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Aspect" value="1"/>
        <details key="Review" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="rating" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Aspect" value="1"/>
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="type" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Aspect" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="author_name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author_url" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="author_url" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="text" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="time" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aspects" lowerBound="1"
        upperBound="-1" eType="#//Aspect">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="aspects" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Review" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="placeDetailInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="placeDetailInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="reference" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeDetailInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeDetailInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="key" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeDetailInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeDetailOutput" lowerBound="1"
        eType="#//PlaceSearchEngineOutput">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="placeDetailOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeDetailInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Geometry" value="2"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="location" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Geometry" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewport" lowerBound="1"
        eType="#//Viewport">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="viewport" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Geometry" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceSearchEngineOutput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="PlaceSearchEngineOutput" value="1"/>
        <details key="PlaceDetailOutput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debug_info" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="debug_info" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceSearchEngineOutput" value="1"/>
          <details key="PlaceDetailOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="html_attributions" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="html_attributions" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceSearchEngineOutput" value="1"/>
          <details key="PlaceDetailOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="next_page_token" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="next_page_token" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceSearchEngineOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" lowerBound="1"
        upperBound="-1" eType="#//Result">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="results" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceSearchEngineOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="status" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceSearchEngineOutput" value="1"/>
          <details key="PlaceDetailOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
        eType="#//Result">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="result" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PlaceDetailOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photo">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Photo" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="height" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Photo" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="html_attributions" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="html_attributions" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Photo" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="photo_reference" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="photo_reference" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Photo" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="width" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Photo" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Viewport">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Viewport" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="northeast" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="northeast" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Viewport" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="southwest" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="southwest" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Viewport" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address_component">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Address_component" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="long_name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="short_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="short_name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="types" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="placeSearchEngineInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="placeSearchEngineInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googlePlaces"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="location" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeSearchEngineInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="radius" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeSearchEngineInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeSearchEngineInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="key" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeSearchEngineInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeSearchEngineOutput"
        lowerBound="1" eType="#//PlaceSearchEngineOutput">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="placeSearchEngineOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="placeSearchEngineInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
