<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="googleMaps" nsURI="http://fr.inria.atlanmod/discovered/googleMaps"
    nsPrefix="composedg">
  <eClassifiers xsi:type="ecore:EClass" name="Step">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Step" value="1"/>
        <details key="Leg" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" lowerBound="1"
        eType="#//Distance">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="distance" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" lowerBound="1"
        eType="#//Distance">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="duration" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end_location" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="end_location" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="html_instructions" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="html_instructions" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="polyline" lowerBound="1"
        eType="#//Overview_polyline">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="polyline" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start_location" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="start_location" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travel_mode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="travel_mode" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Step" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end_address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="end_address" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start_address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="start_address" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="via_waypoint" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="via_waypoint" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//Step">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="steps" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Leg" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Result" value="2"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elevation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="elevation" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="location" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="resolution" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatted_address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="formatted_address" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="types" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address_components" lowerBound="1"
        upperBound="-1" eType="#//Address_component">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="address_components" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" lowerBound="1"
        eType="#//Geometry">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="geometry" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Result" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="pathCalculatorInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="pathCalculatorInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="origin" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="pathCalculatorInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="destination" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="pathCalculatorInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waypoints" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="waypoints" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="pathCalculatorInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="pathCalculatorInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathCalculatorOutput" lowerBound="1"
        eType="#//PathCalculatorOutput">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="pathCalculatorOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="pathCalculatorInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Northeast">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Northeast" value="2"/>
        <details key="End_location" value="1"/>
        <details key="Start_location" value="1"/>
        <details key="Southwest" value="2"/>
        <details key="Location" value="2"/>
      </eAnnotations>
      <details key="totalFound" value="8"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="lat" value="8"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Northeast" value="2"/>
          <details key="End_location" value="1"/>
          <details key="Start_location" value="1"/>
          <details key="Southwest" value="2"/>
          <details key="Location" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="8"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lng" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="lng" value="8"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Northeast" value="2"/>
          <details key="End_location" value="1"/>
          <details key="Start_location" value="1"/>
          <details key="Southwest" value="2"/>
          <details key="Location" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="8"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Distance">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Distance" value="2"/>
        <details key="Duration" value="2"/>
      </eAnnotations>
      <details key="totalFound" value="4"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="text" value="4"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Distance" value="2"/>
          <details key="Duration" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="4"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="value" value="4"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Distance" value="2"/>
          <details key="Duration" value="2"/>
        </eAnnotations>
        <details key="totalFound" value="4"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bound">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Bound" value="1"/>
        <details key="Viewport" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="northeast" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="northeast" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Bound" value="1"/>
          <details key="Viewport" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="southwest" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="southwest" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Bound" value="1"/>
          <details key="Viewport" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="geographicalCodeInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="geographicalCodeInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="address" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="geographicalCodeInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="geographicalCodeInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geographicalCodeOutput"
        lowerBound="1" eType="#//Element">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="geographicalCodeOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="geographicalCodeInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Overview_polyline">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Overview_polyline" value="1"/>
        <details key="Polyline" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="points" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Overview_polyline" value="1"/>
          <details key="Polyline" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="arrayDistanceInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="arrayDistanceInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origins" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="origins" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="destinations" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="mode" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="language" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayDistanceOutput" lowerBound="1"
        eType="#//PathCalculatorOutput">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="arrayDistanceOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="arrayDistanceInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Row" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//Element">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="elements" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Row" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="positionElevationInput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="positionElevationInput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locations" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="locations" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="positionElevationInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sensor" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="positionElevationInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="positionElevationOutput"
        lowerBound="1" eType="#//PathCalculatorOutput">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="positionElevationOutput" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="positionElevationInput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Geometry" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Northeast">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="location" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Geometry" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location_type" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="location_type" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Geometry" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewport" lowerBound="1"
        eType="#//Bound">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="viewport" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Geometry" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Route" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" lowerBound="1"
        eType="#//Bound">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="bounds" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="copyrights" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="copyrights" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legs" lowerBound="1" upperBound="-1"
        eType="#//Step">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="legs" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overview_polyline" lowerBound="1"
        eType="#//Overview_polyline">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="overview_polyline" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="summary" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warnings" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="warnings" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waypoint_order" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="waypoint_order" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Route" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address_component">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Address_component" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="long_name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="short_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="short_name" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="types" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="types" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Address_component" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Element" value="1"/>
        <details key="GeographicalCodeOutput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="distance" lowerBound="1"
        eType="#//Distance">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="distance" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Element" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duration" lowerBound="1"
        eType="#//Distance">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="duration" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Element" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="status" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Element" value="1"/>
          <details key="GeographicalCodeOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" lowerBound="1"
        upperBound="-1" eType="#//Result">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="results" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="GeographicalCodeOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathCalculatorOutput">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="PathCalculatorOutput" value="1"/>
        <details key="PositionElevationOutput" value="1"/>
        <details key="ArrayDistanceOutput" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="3"/>
      <details key="source" value="googleMaps"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" lowerBound="1"
        upperBound="-1" eType="#//Route">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="routes" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PathCalculatorOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="status" value="3"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PathCalculatorOutput" value="1"/>
          <details key="PositionElevationOutput" value="1"/>
          <details key="ArrayDistanceOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="3"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" lowerBound="1"
        upperBound="-1" eType="#//Result">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="results" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="PositionElevationOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination_addresses"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="destination_addresses" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="ArrayDistanceOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="origin_addresses" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="origin_addresses" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="ArrayDistanceOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="1" upperBound="-1"
        eType="#//Row">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="rows" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="ArrayDistanceOutput" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
