<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="coverage" nsURI="http://fr.inria.atlanmod/json/coverage" nsPrefix="coverage">
  <eClassifiers xsi:type="ecore:EClass" name="Coverage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" lowerBound="1"
        upperBound="-1" eType="#//CoverageMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageMapping" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttMapping" eSuperTypes="#//CoverageMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefMapping" eSuperTypes="#//CoverageMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConceptMapping" eSuperTypes="#//CoverageMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
</ecore:EPackage>
