/*
 * generated by Xtext
 */
package fr.inria.atlanmod.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends fr.inria.atlanmod.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
