/*
 * generated by Xtext
 */
package fr.inria.atlanmod.ui;

import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonActivator implements BundleActivator {

	private static JsonActivator INSTANCE;
	private static BundleContext context;
	

	static BundleContext getContext() {
		return context;
	}

	@Override
	public void start(BundleContext context) throws Exception {
		INSTANCE = this;
	}

	@Override
	public void stop(BundleContext context) throws Exception {
		INSTANCE = null;
	}

	public static JsonActivator getInstance() {
		return INSTANCE;
	}
}
