/*
* generated by Xtext
*/
package fr.inria.atlanmod.ui.contentassist;

import fr.inria.atlanmod.ui.contentassist.AbstractJsonProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JsonProposalProvider extends AbstractJsonProposalProvider {

}
