<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="composed" nsURI="http://jsondiscoverer/discovered/composed"
    nsPrefix="composedc">
  <eClassifiers xsi:type="ecore:EClass" name="HorariesStopLineDirection">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="HorariesStopLineDirection" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arret" lowerBound="1" eType="#//Arret">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="arret" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ligne" lowerBound="1" eType="#//Ligne">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ligne" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeCouleur" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="codeCouleur" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plageDeService" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="plageDeService" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" lowerBound="1" upperBound="-1"
        eType="#//Note">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="notes" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="horaires" lowerBound="1"
        upperBound="-1" eType="#//ProchainsHoraire">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="horaires" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prochainsHoraires" lowerBound="1"
        upperBound="-1" eType="#//ProchainsHoraire">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="prochainsHoraires" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="HorariesStopLineDirection" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ligne">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Ligne" value="3"/>
      </eAnnotations>
      <details key="totalFound" value="3"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numLigne" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="numLigne" value="3"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="3"/>
        </eAnnotations>
        <details key="totalFound" value="3"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directionSens1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="directionSens1" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directionSens2" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="directionSens2" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="accessible" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etatTrafic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="etatTrafic" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelleTrafic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="libelleTrafic" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeLigne" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="typeLigne" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Ligne" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.3333333333333333"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StopPosition">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="StopPosition" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeLieu" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="codeLieu" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="StopPosition" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="libelle" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="StopPosition" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="distance" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="StopPosition" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ligne" lowerBound="1" upperBound="-1"
        eType="#//Ligne">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ligne" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="StopPosition" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Note" value="1"/>
        <details key="Arret" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="code" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Note" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="libelle" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Note" value="1"/>
          <details key="Arret" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeArret" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="codeArret" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Arret" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="accessible" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Arret" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="0.5"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProchainsHoraire">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="ProchainsHoraire" value="1"/>
        <details key="Horaire" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="2"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heure" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="heure" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="ProchainsHoraire" value="1"/>
          <details key="Horaire" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passages" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="passages" value="2"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="ProchainsHoraire" value="1"/>
          <details key="Horaire" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="2"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arret">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="Arret" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeArret" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="codeArret" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="Arret" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitingTimeStop">
    <eAnnotations source="coverage">
      <eAnnotations source="AlsoKnownAs">
        <details key="WaitingTimeStop" value="1"/>
      </eAnnotations>
      <details key="totalFound" value="1"/>
      <details key="source" value="composed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sens" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="sens" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="terminus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="terminus" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infotrafic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="infotrafic" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temps" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="temps" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ligne" lowerBound="1" eType="#//Ligne">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="ligne" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arret" lowerBound="1" eType="#//Arret">
      <eAnnotations source="coverage">
        <eAnnotations source="AlsoKnownAs">
          <details key="arret" value="1"/>
        </eAnnotations>
        <eAnnotations source="foundIn">
          <details key="WaitingTimeStop" value="1"/>
        </eAnnotations>
        <details key="totalFound" value="1"/>
        <details key="ratioTotalFound" value="1.0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
