/*
* generated by Xtext
*/
package fr.inria.atlanmod;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JsonUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.inria.atlanmod.ui.internal.JsonActivator.getInstance().getInjector("fr.inria.atlanmod.Json");
	}
	
}
